name:                advent2018
version:             0.1.0.0
github:              "shterrett/advent2018"
license:             BSD3
author:              "Stuart Terrett"
maintainer:          "shterrett@gmail.com"
copyright:           "Copyright 2018 Stuart Terrett"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/shterrett/advent2018#readme>

dependencies:
- base >= 4.7 && < 5
- text
- unordered-containers
- parsec
- parsers

library:
  source-dirs: src

executables:
  advent2018-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent2018

tests:
  advent2018-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent2018
    - hspec
